<?php
namespace CAG\T3footnotes\Controller;


/***
 *
 * This file is part of the "Fuss" Extension for TYPO3 CMS.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 *
 *  (c) 2019 
 *
 ***/
/**
 * FootnoteController
 */
class FootnoteController extends \TYPO3\CMS\Extbase\Mvc\Controller\ActionController
{

    /**
     * action list
     * 
     * @return void
     */
    public function listAction()
    {
        // Action to render static container für t3footnotes generated by contentPostProc-cached Hook
    }


}
